# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Moai_iOS' do
  pod 'Kingfisher', '~> 6.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Moai_iOS

end
